version: 2.1
orbs:
    gcp-cli: circleci/gcp-cli@2.4.1
jobs:
    test:
        docker:
            - image: 'cimg/node:14.17-browsers'
              environment:
                  DATABASE_URL: mongodb://localhost:27017/test
                  TOKEN_KEY: fjAJ4mv0WRlc7ob1Dq7J
            - image: 'mongo'
        steps:
            - checkout
            - run: sudo npm i pnpm@latest-6 -g
            - run:
                  command: pnpm i -F schemas && pnpm i
                  name: Install dependencies
            - run:
                  command: pnpm lint
                  name: Lint projects

            # TODO: UNCOMMENT
            # - run:
            #       command: pnpm test
            #       name: Run Unit Tests
    deploy:
        docker:
            - image: 'cimg/node:14.17-browsers'
        steps:
            # TODO: deploy image
            - checkout
            - setup_remote_docker:
                  version: 20.10.12
                  docker_layer_caching: true
            - run: sudo npm i pnpm@latest-6 -g
            - run:
                  name: Install Docker Compose
                  environment:
                      COMPOSE_VERSION: '1.29.2'
                  command: |
                      curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                      chmod +x ~/docker-compose
                      sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run: pnpm i -F schemas && pnpm i
            - run:
                  name: Isolate API workspace
                  command: |
                      pnpm isolate -F nest-api
            - run:
                  name: Build API Docker image
                  command: docker-compose build
            - run:
                  name: Push API Docker image
                  command: |
                      docker tag project_api europe-north1-docker.pkg.dev/mewi-347117/mewi-docker-repo/mewi-api
                      docker push europe-north1-docker.pkg.dev/mewi-347117/mewi-docker-repo/mewi-api
workflows:
    version: 2
    build_test_and_deploy:
        jobs:
            - test:
                  filters:
                      branches:
                          only:
                              - main
            - gcp-cli/install_and_initialize_cli:
                  executor: gcp-cli/default
            - deploy:
                  filters:
                      branches:
                          only:
                              - main
                  requires:
                      - test
    build_and_test:
        jobs:
            - hold:
                  type: approval
                  filters:
                      branches:
                          only:
                              - dev
            - test:
                  requires:
                      - hold
