version: 2.1
orbs:
  nx: nrwl/nx@1.1.3
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run:
          command: npm install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas:
          error-on-no-successful-workflow: true
          main-branch-name: main
      - run:
          command: npx nx affected --target=build --base=$NX_BASE
          name: Run Builds
      - run:
          command: npx nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests
  deploy_netlify:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run: npm install
      - run:
          command: nx deploy webapp
          name: Deploy webapp to Netlify
  deploy_to_okteto:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: pwd
      - run:
          command: curl https://get.okteto.com -sSfL | sh
          name: Install Okteto CLI
      - run:
          command: okteto login --token $OKTETO_TOKEN
          name: Login in to Okteto
      - checkout
      - run:
          command: okteto build --file ./packages/api/Dockerfile --tag okteto.dev/api
          name: Build API image
      - run:
          command: okteto pipeline deploy
          name: Deploy pipeline
          
workflows:
    version: 2
    build_test_and_deploy:
      jobs:
        - deploy_to_okteto
        # - build_and_test
        # - deploy_netlify:
        #     requires:
        #       - build_and_test
