version: 2.1
orbs:
  nx: nrwl/nx@1.1.3
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run:
          command: npm install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas:
          error-on-no-successful-workflow: true
          main-branch-name: main
      - run:
          command: npx nx affected --target=build --base=$NX_BASE
          name: Run Builds
      - run:
          command: npx nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests
  deploy:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run: npm install
      - run:
          command: nx deploy webapp
          name: Deploy webapp to Netlify
  build_api_image:
    docker:
     - image: 'docker:17.05.0-ce-git'
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run:
          command: docker build -f ./packages/api/Dockerfile . -t api
          name: Deploy API to Okteto
  deploy_to_okteto:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          command: curl https://get.okteto.com -sSfL | sh
          name: Install Okteto CLI
      - run:
          command: okteto login --token $OKTETO_TOKEN
          name: Login in to Okteto
      - checkout
      - run: okteto pipeline deploy
          
workflows:
    version: 2
    build_test_and_deploy:
      jobs:
        - build_api_image
        - deploy_to_okteto
        # - build_and_test
        # - deploy:
        #     requires:
        #       - build_and_test
        # - deploy_backend:
        #     requires:
        #       - build_and_test
