version: 2.1
jobs:
    test:
        docker:
            - image: 'cimg/node:14.17-browsers'
              environment:
                  MONGO_URI: localhost
                  TOKEN_KEY: fjAJ4mv0WRlc7ob1Dq7J
                  SEARCH_ENGINE_URL: localhost
                  SEARCH_ENGINE_PORT: 9200
            - image: 'mongo'
        steps:
            - checkout
            - run: sudo npm i pnpm@latest-6 -g
            - run:
                  command: pnpm i
                  name: Install dependencies
            - run:
                  command: pnpm lint
                  name: Lint projects
            - run:
                  command: pnpm build
                  name: Run Builds

            # TODO: UNCOMMENT
            # - run:
            #       command: pnpm test
            #       name: Run Unit Tests
            - persist_to_workspace:
                  root: .
                  paths:
                      - '*'
    deploy:
        docker:
            - image: 'cimg/node:14.17-browsers'
        steps:
            # TODO: deploy image
            - checkout
            - attach_workspace:
                  at: .
            - setup_remote_docker:
                  version: 20.10.12
                  docker_layer_caching: true
            - run: sudo npm i pnpm@latest-6 -g
            - run:
                  name: Install Docker Compose
                  environment:
                      COMPOSE_VERSION: '1.29.2'
                  command: |
                      curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                      chmod +x ~/docker-compose
                      sudo mv ~/docker-compose /usr/local/bin/docker-compose
            -run:
                name: Login to Heroku
                command: |
                    (
                        echo "$HEROKU_EMAIL"
                        echo "$HEROKU_PASSWORD"
                    ) | heroku login
                    heroku auth:token | sudo docker login --username=_ registry.heroku.com --password-stdin
            - run:
                  name: Isolate API workspace
                  command: |
                      pnpm isolate -F nest-api
            - run:
                  name: Build API Docker image
                  command: |
                      sudo docker-compose build -d api
            - run:
                  name: Push API Docker image
                  command: |
                      docker tag api registry.heroku.com/mewi-api/web
                      docker push registry.heroku.com/mewi-api/web
workflows:
    version: 2
    build_test_and_deploy:
        jobs:
            - test:
                  filters:
                      branches:
                          only:
                              - main
            - deploy:
                  filters:
                      branches:
                          only:
                              - main
                  requires:
                      - test
    build_and_test:
        jobs:
            - hold:
                  type: approval
                  filters:
                      branches:
                          only:
                              - dev
            - test:
                  requires:
                      - hold
