version: 2.1
orbs:
  nx: nrwl/nx@1.1.3
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run:
          command: npm install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas:
          error-on-no-successful-workflow: true
          main-branch-name: main
      - run:
          command: npx nx affected --target=build --base=$NX_BASE
          name: Run Builds
      - run:
          command: npx nx affected --target=test --base=$NX_BASE
          name: Run Unit Tests
  deploy:
    docker:
      - image: 'cimg/node:14.17-browsers'
    steps:
      - checkout
      - run: npm install
      - run:
          command: nx deploy webapp
          name: Deploy webapp to Netlify
  deploy_backend:
    docker:
     - image: 'docker:17.05.0-ce-git'
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run:
          command: docker build -f ./packages/api/Dockerfile . -t api
          name: Deploy API to Okteto
workflows:
    version: 2
    build_test_and_deploy:
      jobs:
        - deploy_backend
        # - build_and_test
        # - deploy:
        #     requires:
        #       - build_and_test
        # - deploy_backend:
        #     requires:
        #       - build_and_test
