apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: api
    name: api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            imagePullSecrets:
            - name: regcred
            containers:
                - image: wille430/mewi-api:latest
                  name: mewi-api
                  env:
                      - name: SEARCH_ENGINE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: elastic-configmap
                                key: elastic_url
                      - name: SEARCH_ENGINE_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: elastic-configmap
                                key: elastic_port
                      - name: MONGO_URI
                        value: mongodb-service:27017
                      - name: MONGO_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: admin_username
                      - name: MONGO_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: admin_password
                      - name: GMAIL_MAIL
                        valueFrom:
                            secretKeyRef:
                                name: gmail-secret
                                key: gmail_mail
                      - name: GMAIL_PASS
                        valueFrom:
                            secretKeyRef:
                                name: gmail-secret
                                key: gmail_pass
                      - name: TOKEN_KEY
                        value: minecraft
                  # - name: MEILI_MASTER_KEY
                  #   valueFrom:
                  #     secretKeyRef:
                  #       name: meilisearch-secret
                  #       key: meili_master_key
---
apiVersion: v1
kind: Service
metadata:
    name: api-svc
spec:
    type: LoadBalancer
    selector:
        app: api
    ports:
        - protocol: TCP
          port: 3001
          targetPort: 3001
