apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: elasticsearch
    labels:
        app: elasticsearch
spec:
    replicas: 1
    serviceName: 'elasticsearch'
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            labels:
                app: elasticsearch
        spec:
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
                  volumeMounts:
                      - mountPath: '/usr/share/elasticsearch/data'
                        name: elasticdata
                  ports:
                      - containerPort: 9200
                  env:
                      - name: 'cluster.initial_master_nodes'
                        value: 'elasticsearch-0'
            initContainers:
              - name: init-elasticsearch
                image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
                command:
                - chown
                - -R
                - 1000:1000
                - /usr/share/elasticsearch/data
            volumes:
                - name: elasticdata
                  persistentVolumeClaim:
                      claimName: elasticsearch-pv-claim

---
apiVersion: v1
kind: Service
metadata:
    name: elasticsearch-service
spec:
    selector:
        app: elasticsearch
    ports:
        - protocol: TCP
          port: 9200
          targetPort: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: elasticsearch-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
