apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb
    labels:
        app: mongodb
spec:
    replicas: 1
    serviceName: 'mongodb'
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo
                  volumeMounts:
                      - mountPath: '/data/db'
                        name: mongodata
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: admin_username
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: admin_password
            volumes:
                - name: mongodata
                  persistentVolumeClaim:
                      claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
spec:
    selector:
        app: mongodb
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
