apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    admin_username: cm9vdA==
    admin_password: cGFzc3dvcmQ=
    express_username: cm9vdA==
    express_password: cGFzc3dvcmQ=
