version: "3.7"
name: "mewi"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_go_net
  scrape-service:
    container_name: scrape-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        FOLDER: apps/scrape-service
        SCOPE: scrape-service
    environment:
      - "MQ_CONNECTION_STRING=amqp://username:password@rabbitmq:5672"
      - "MONGO_URI=mongodb://mongo1:27017/test?directConnection=true"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
      - mewi_mongo-network

  notification-service:
    container_name: notification-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        FOLDER: apps/notification-service
        SCOPE: notification-service
    environment:
      - "MQ_CONNECTION_STRING=amqp://username:password@rabbitmq:5672"
      - "MONGO_URI=mongodb://mongo1:27017/test?directConnection=true"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
      - mewi_mongo-network

networks:
  rabbitmq_go_net:
    driver: bridge
  mewi_mongo-network:
    external: true
