version: "3.7"
services:
  email-service:
    container_name: email-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        FOLDER: apps/email-service
        SCOPE: email-service