version: "3.7"
name: mewi
services:
  scrape-service:
    container_name: scrape-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: app1
      args:
        FOLDER: apps/scrape-service
        SCOPE: scrape-service
  notfification-service:
    container_name: notification-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: app2
      args:
        FOLDER: apps/notification-service
        SCOPE: notification-service
