import { Category } from '@wille430/common'
import { BlocketListing } from './types/blocketListing'

export const parseTraderaCategories = (category: string): Category => {
    return traderaKeyValuePair[category] || []
}

const traderaKeyValuePair = {
    Accessoarer: ['personligt', 'accessoarer_klockor'],
    'Antikt & Design': ['för_hemmet', 'möbler_hemindredning'],
    'Barnkläder & Barnskor': ['personligt', 'barnkläder_skor'],
    'Biljetter & Resor': ['fritid_hobby', 'upplevelser_nöje'],
    'Bygg & Verktyg': ['för_hemmet', 'bygg_trädgård', 'Verktyg'],
    'Böcker & Tidningar': ['fritid_hobby', 'böcker_studentlitteratur'],
    'Datorer & Tillbehör': ['elektronik', 'datorer_tv-spel'],
    'DVD & Videofilmer': ['elektronik', 'ljud_bild'],
    'Fordon, Båtar & Delar': ['fordon', 'båtar', 'båtdelar_tillbehör'],
    'Foto, Kameror & Optik': ['elektronik', 'ljud_bild'],
    Frimärken: ['fritid_hobby', 'hobby_samlarprylar'],
    'Handgjort & Konsthantverk': ['för_hemmet'],
    'Hem & Hushåll': ['för_hemmet', 'möbler_hemindredning'],
    Hemelektronik: ['elektronik'],
    Hobby: ['fritid_hobby'],
    Klockor: ['personligt', 'accessoarer_klockor'],
    Kläder: ['personligt', 'kläder_skor'],
    Konst: ['för_hemmet', 'möbler_hemindredning'],
    'Leksaker & Barnartiklar': ['personligt', 'barnartiklar_leksaker'],
    'Mobiltelefoni & Tele': ['elektronik', 'telefoner_tillbehör'],
    Musik: ['elektronik', 'ljud_bild'],
    'Mynt & Sedlar': ['fritid_hobby', 'hobby_samlarprylar'],
    Samlarsaker: ['fritid_hobby', 'hobby_samlarprylar'],
    Skor: ['personligt', 'kläder_skor'],
    Skönhetsvård: ['personligt'],
    'Smycken & Ädelstenar': ['personligt', 'accessoarer_klockor'],
    'Sport & Fritid': ['fritid_hobby', 'sport-_fritidsutrustning'],
    'Trädgård & Växter': ['för_hemmet', 'bygg_trädgård'],
    'TV-spel & Datorspel': ['elektronik', 'datorer_tv-spel'],
    'Vykort & Bilder': ['fritid_hobby'],
    Övrigt: ['övrigt'],
}

const blocketKeyValuePair = {
    Fordon: 'fordon',
    Bilar: 'bilar',
    Båtar: 'båtar',
    'Bildelar & biltillbehör': 'bildelar_biltillbehör',
    Mopeder: 'mopeder',
    'Båtdelar & tillbehör': 'båtdelar_tillbehör',
    'Husvagnar & husbilar': 'husvagnar_husbilar',
    'MC-delar': 'mc-delar',
    'A-traktor': 'a-traktor',
    'Lastbil, truck': 'lastbil_truck_entreprenad',
    Motorcyklar: 'motorcyklar',
    Snöskotrar: 'snöskotrar',
    Snöskoterdelar: 'snöskoterdelar',
    'För hemmet': 'för_hemmet',
    'Bygg & trädgård': 'bygg_trädgård',
    'Husgeråd & vitvaror': 'husgeråd_vitvaror',
    'Möbler & hemindredning': 'möbler_hemindredning',
    Verktyg: 'verktyg',
    Bostad: 'bostad',
    Lägenheter: 'lägenheter',
    Villor: 'villor',
    Radhus: 'radhus',
    Tomter: 'tomter',
    Gårdar: 'gårdar',
    Fritidsboende: 'fritidsboende',
    Utland: 'utland',
    Personligt: 'personligt',
    'Kläder & skor': 'kläder_skor',
    'Accessoarer & klockor': 'accessoarer_klockor',
    'Barnartiklar & leksaker': 'barnartiklar_leksaker',
    'Barnkläder & skor': 'barnkläder_skor',
    Elektronik: 'elektronik',
    'Datorer & TV-spel': 'datorer_tv-spel',
    'Ljud & bild': 'ljud_bild',
    'Telefoner & tillbehör': 'telefoner_tillbehör',
    'Fritid & hobby': 'fritid_hobby',
    'Upplevelser & nöje': 'upplevelser_nöje',
    'Böcker & studentlitteratur': 'böcker_studentlitteratur',
    Cyklar: 'cyklar',
    Djur: 'djur',
    'Hobby & samlarprylar': 'hobby_samlarprylar',
    'Hästar & ridsport': 'hästar_ridsport',
    'Jakt & fiske': 'jakt_fiske',
    Musikutrustning: 'musikutrustning',
    'Sport- & fritidsutrustning': 'sport-_fritidsutrustning',
    Affärsverksamhet: 'affärsverksamhet',
    Affärsöverlåtelser: 'affärsöverlåtelser',
    'Inventarier & maskiner': 'inventarier_maskiner',
    'Lokaler & fastigheter': 'lokaler_fastigheter',
    Tjänster: 'tjänster',
    Övrigt: 'övrigt',
}
