export enum Category {
    FORDON = 'FORDON',
    FOR_HEMMET = 'FOR_HEMMET',
    PERSONLIGT = 'PERSONLIGT',
    ELEKTRONIK = 'ELEKTRONIK',
    FRITID_HOBBY = 'FRITID_HOBBY',
    AFFARSVERKSAMHET = 'AFFARSVERKSAMHET',
    OVRIGT = 'OVRIGT',
}
