export const TraderaCategories = [
    { href: '/category/1612', title: 'Accessoarer' },
    { href: '/category/20', title: 'Antikt & Design' },
    { href: '/category/1611', title: 'Barnartiklar' },
    { href: '/category/33', title: 'Barnkläder & Barnskor' },
    { href: '/category/302571', title: 'Barnleksaker' },
    { href: '/category/34', title: 'Biljetter & Resor' },
    { href: '/category/32', title: 'Bygg & Verktyg' },
    { href: '/category/11', title: 'Böcker & Tidningar' },
    { href: '/category/12', title: 'Datorer & Tillbehör' },
    { href: '/category/13', title: 'DVD & Videofilmer' },
    { href: '/category/10', title: 'Fordon, Båtar & Delar' },
    { href: '/category/14', title: 'Foto, Kameror & Optik' },
    { href: '/category/15', title: 'Frimärken' },
    { href: '/category/36', title: 'Handgjort & Konsthantverk' },
    { href: '/category/31', title: 'Hem & Hushåll' },
    { href: '/category/17', title: 'Hemelektronik' },
    { href: '/category/18', title: 'Hobby' },
    { href: '/category/19', title: 'Klockor' },
    { href: '/category/16', title: 'Kläder' },
    { href: '/category/23', title: 'Konst' },
    { href: '/category/21', title: 'Musik' },
    { href: '/category/22', title: 'Mynt & Sedlar' },
    { href: '/category/29', title: 'Samlarsaker' },
    { href: '/category/1623', title: 'Skor' },
    { href: '/category/340736', title: 'Skönhetsvård' },
    { href: '/category/24', title: 'Smycken & Ädelstenar' },
    { href: '/category/25', title: 'Sport & Fritid' },
    { href: '/category/26', title: 'Telefoni, Tablets & Wearables' },
    { href: '/category/1605', title: 'Trädgård & Växter' },
    { href: '/category/30', title: 'TV-spel & Datorspel' },
    { href: '/category/27', title: 'Vykort & Bilder' },
]
